project:
  type: website
  output-dir: ../docs


website:
  page-navigation: true
  search: false
  page-footer:
    border: false
    background: transparent
    foreground: DimGray
    #left: Left content
    #right: Right content
  navbar:
    background: transparent
    pinned: true
    left:
      - file: "https://chaishekar.github.io/Portfolio/"
        text: Home
      - file: "gender.qmd#intro"
        text: Introduction
      - text: Methodology
        menu:
        - text: Data
          href: "gender.qmd#data"
        - text: Models
          href: "gender.qmd#models"
        - text: Results
          href: "gender.qmd#results"
      - text: Conclusion
        href: "gender.qmd#conclusion"

    right:
      - icon: github
        href: https://github.com/chaishekar/Gender-Inequality-Across-the-World


        

format:
  html:
    theme: 
      - styles.scss
    toc: false

editor: visual
